[tool.poetry]
name = "lab1-fastapinovosad"
version = "0.1.0"
description = ""
authors = ["Bohdan <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "<0.100"
uvicorn = "^0.41.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
